#!/bin/bash

jupyter labextension install @jupyterlab/git
pip install --upgrade jupyterlab-git
jupyter serverextension enable --py jupyterlab_git
nbdime extensions --enable

jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38
jupyter labextension install jupyter-leaflet
